### ISSUE TITLE
Cannot find model

### ISSUE THREAD

**Issue by zzk1st** [lightonai/RITA#7]
Hi! I'm trying to run the example and have met the following errors:

```
>>> model = AutoModelForCausalLM.from_pretrained("lightonai/RITA_s, trust_remote_code=True")
Traceback (most recent call last):
  File "/data/home/zhongkai/miniconda/envs/protein_ssf_aws/lib/python3.8/site-packages/transformers/configuration_utils.py", line 601, in _get_config_dict
    resolved_config_file = cached_path(
  File "/data/home/zhongkai/miniconda/envs/protein_ssf_aws/lib/python3.8/site-packages/transformers/utils/hub.py", line 284, in cached_path
    output_path = get_from_cache(
  File "/data/home/zhongkai/miniconda/envs/protein_ssf_aws/lib/python3.8/site-packages/transformers/utils/hub.py", line 495, in get_from_cache
    _raise_for_status(r)
  File "/data/home/zhongkai/miniconda/envs/protein_ssf_aws/lib/python3.8/site-packages/transformers/utils/hub.py", line 417, in _raise_for_status
    raise RepositoryNotFoundError(
transformers.utils.hub.RepositoryNotFoundError: 401 Client Error: Repository not found for url: https://huggingface.co/lightonai/RITA_s,%20trust_remote_code=True/resolve/main/config.json. If the repo is private, make sure you are authenticated.
```

What am I doing wrong here? Appreciate the help, thanks!

**Comment by DanielHesslow** [comment]
Sorry, there's was a typo in the readme, fixed in #4, 

``` python
("lightonai/RITA_s, trust_remote_code=True")
```
should be 
``` python
("lightonai/RITA_s", trust_remote_code=True)
```
